// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/HUD/StanceVelocityInfo/StanceVelocityInfo.layout

class PAG_StanceVelocityInfoWidgets
{
	static const ResourceName s_sLayout = "{ABDDFF3E68CF4307}UI/layouts/HUD/StanceVelocityInfo/StanceVelocityInfo.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ProgressBarWidget m_Stance;

	ProgressBarWidget m_Speed;

	ProgressBarWidget m_Stamina;

	ProgressBarWidget m_Health;

	ProgressBarWidget m_Blood;

	bool Init(Widget root)
	{
		m_Stance = ProgressBarWidget.Cast(root.FindAnyWidget("m_Stance"));

		m_Speed = ProgressBarWidget.Cast(root.FindAnyWidget("m_Speed"));

		m_Stamina = ProgressBarWidget.Cast(root.FindAnyWidget("m_Stamina"));

		m_Health = ProgressBarWidget.Cast(root.FindAnyWidget("m_Health"));

		m_Blood = ProgressBarWidget.Cast(root.FindAnyWidget("m_Blood"));

		return true;
	}
}
